-- CV upload pipeline.
-- Each row represents one secure upload "slot" for a doctor — a token-gated
-- URL the team sends to the doctor. When the doctor uploads a CV via that
-- URL, the file lands in Supabase Storage and Claude extracts profile fields
-- into doctor_profiles.
--
-- Lifecycle:
--   pending_upload   — link sent, no file yet
--   uploaded         — file stored, extraction queued
--   extracting       — Claude API in flight
--   extracted        — fields parsed; doctor_profiles upserted (needs_review)
--   failed           — extraction failed (LLM error, malformed CV, etc.)

create table if not exists public.cv_uploads (
  id                  uuid primary key default gen_random_uuid(),
  doctor_id           text not null,
  doctor_name         text not null,
  doctor_email        text,
  -- URL-safe random token. The /upload-cv/:token public route resolves this
  -- → loads the row → shows the upload form. Generated by the
  -- send-cv-upload-link function so it can be embedded in the outgoing email.
  token               text unique not null,
  -- supabase storage path inside the doctor-cvs bucket, e.g.
  -- "<doctor_id>/<token>/cv.pdf". Set when the upload completes.
  file_path           text,
  file_name           text,
  file_size           int,
  file_mime           text,
  uploaded_at         timestamptz,
  status              text not null default 'pending_upload',
  -- Raw Claude response (the structured extraction). Kept for debugging and
  -- so the team can see exactly what was inferred before reviewing.
  extracted_data      jsonb,
  extraction_error    text,
  extracted_at        timestamptz,
  -- Soft expiry. Links beyond expires_at are rejected by the upload handler.
  expires_at          timestamptz not null default (now() + interval '90 days'),
  created_at          timestamptz not null default now(),
  created_by          text
);

create index if not exists cv_uploads_doctor_idx  on public.cv_uploads (doctor_id);
create index if not exists cv_uploads_token_idx   on public.cv_uploads (token);
create index if not exists cv_uploads_status_idx  on public.cv_uploads (status);

alter table public.cv_uploads enable row level security;

drop policy if exists "service role full cv_uploads" on public.cv_uploads;
drop policy if exists "auth read cv_uploads"        on public.cv_uploads;
drop policy if exists "auth insert cv_uploads"      on public.cv_uploads;

create policy "service role full cv_uploads" on public.cv_uploads for all to service_role using (true) with check (true);
create policy "auth read cv_uploads"         on public.cv_uploads for select to authenticated using (true);
create policy "auth insert cv_uploads"       on public.cv_uploads for insert to authenticated with check (true);

-- ── Storage bucket for the actual CV files ──────────────────────────────────
-- Private bucket — no public reads. The cv-upload-public edge function writes
-- with service_role; the cv-extract function reads with service_role. The
-- dashboard renders signed URLs when a team member wants to download a CV.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'doctor-cvs', 'doctor-cvs', false,
  10485760,  -- 10MB
  array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']
)
on conflict (id) do update set
  file_size_limit    = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Allow authenticated users (dashboard team members) to download CVs they
-- already have signed URLs for. Inserts are done exclusively by service_role
-- from the upload edge function (which validates the token first).
drop policy if exists "auth read doctor-cvs" on storage.objects;
create policy "auth read doctor-cvs" on storage.objects
  for select to authenticated
  using (bucket_id = 'doctor-cvs');
